config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  resources :tasks
  resources :departments
  resources :projects
  resources :users, only: [:show]
  resources :user_projects, except: [:destroy]
  resources :user_tasks

  patch '/task-complete' => 'tasks#toggle'
  # custom route for toggling task

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord

	has_many :users
	has_many :projects, dependent: :destroy

end

app/models/project.rb
class Project < ApplicationRecord
  
  belongs_to :department
  has_many :tasks, dependent: :destroy

  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects


end

app/models/task.rb
class Task < ApplicationRecord

	belongs_to :project
	has_many :task_users, dependent: :destroy
	has_many :users, through: :task_users

def completed
	self.complete === true;
end
end

app/models/task_user.rb
class TaskUser < ApplicationRecord

	belongs_to :user
	belongs_to :task

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  belongs_to :department, optional: true

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  has_many :task_users, dependent: :destroy
  has_many :tasks, through: :task_users
  has_many :user_projects, dependent: :destroy
  has_many :projects, through: :user_projects

  def name
    self.first_name + " " + self.last_name
  end

end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  
  def index
    @departments = Department.includes(:projects).references(:projects).all
    @users = User.all
  end

  def show
    @department = Department.find(params[:id])
    @projects = @department.projects.all
    @project_new = Project.new
    @users = @department.users

  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.create(department_params)
    redirect_to @department
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    @department.update(department_params)

    redirect_to @department
  end

  def destroy
    @department = Department.find(params[:id]).destroy
    respond_to do |format|
      format.js
      format.html {redirect_to departments_path}
    end
  end

  private

  def department_params
    params.require(:department).permit(:name, :id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to current_user
  	else
  		redirect_to new_user_session_path
  	end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
    @project_new = Project.new
  end

  def create
    @users = User.all
    @project = Project.create(project_params)
    assign_users
    if @project.save!
      redirect_to @project
    end
  end

  def show
    @projects = Project.all
    @project = Project.find(params[:id])
    @tasks = @project.tasks.all
    @users = User.all
    @department = @project.department
    @team = @project.users
  end

  def edit
    @project = Project.find(params[:id])
    @department = @project.department
    @users = User.all
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    @project.users.destroy_all
    @team = @project.users
    user_ids = params[:project][:user_ids]
    user_ids.each do |user_id|
      if !user_id.blank?
        @project.users << User.find(user_id)
      else
      end
    end
    redirect_to @project
  end

  def destroy
    respond_to do |format|
      @project = Project.find(params[:id]).destroy
      format.js
      format.html{redirect_to departments_path}
    end
  end

  private

  def assign_users
    user_ids = params[:project][:user_ids]
    user_ids.each do |user_id|
      if !user_id.blank? 
        @project.users << User.find(user_id)
      else
      end
    end
  end

  def project_params
    params.require(:project).permit(:department_id, :name, :description, :deadline, :id, :user_ids)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    respond_to do |format|
      @task = Task.new(task_params)
      @users = User.all
      format.js
      format.html
      assign_users
    end
  end

  def update
    @users = User.all
  	respond_to do |format|
	  	@task = Task.find(params[:id])
      @project = @task.project
      @tasks = @project.tasks.all
      @task.update(task_params)
      @task.users.destroy_all
      assign_users
	  	if @task.save!
        format.js
	  		format.html {render project_path(project)}
	  	end
	  end
  end

  def destroy
    respond_to do |format|
      @task = Task.find(params[:id]).destroy
      format.js
      format.html{redirect_to @projects}
    end
  end

# toggle method is run when complete switch is clicked
  def toggle
    respond_to do |format|
      #toggle task
      @task = Task.find(params[:id])
      @task.update(complete: params[:complete])
      #add and subtract points from user
      if params[:complete] == "true"
        @task.users.each do |user|
          user.points += @task.points
          user.save
        end #loop
      else
        @task.users.each do |user|
          user.points -= @task.points
          user.save
        end #loop
      end #ifelse
      format.js
    end #respond_to
  end

  private

  def assign_users
    user_ids = params[:task][:user_ids]
    user_ids.each do |user_id|
      if !user_id.blank? 
        @task.users << User.find(user_id)
      else
      end
      if @task.save
      end
    end
  end

  def task_params
    params.require(:task).permit(:project_id, :name, :description, :deadline, :complete, :task_id, :points, :user_ids)
  end
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController

  def create
    
  end

  def destroy
  end
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  def create
  	
  end

  def destroy
  	respond_to do |format|
			TaskUser.find(params[:id]).destroy
  		format.js
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(params[:id])
   @projects = @user.projects
   @tasks = Task.all
   @tasks = @user.tasks
   @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/departments/_department.html.erb
<div class="card col s6 department department-<%= department.id %>">
  <div class="card-content">
    <span class="card-title">
      <%= link_to department.name, department_path(department), class: "collection-item department-#{department.id} " %>
      </span>
     <div class="project-container">
      <% department.projects.all.each do |project| %>
         <div class="collection">
            <%= link_to project.name, project, class: "collection-item" %>
            <%= link_to "Delete", project, method: :delete, remote: :true, class: "destroy_project float_right" %>
          </div>
       <% end %>
     </div>
  </div>
  <div class="card-action">
    <%= link_to "Edit", edit_department_path(department) %>
    <%= link_to "Delete", department, method: :delete, remote: :true, class: "float_right destroy_d"%>
  </div>
</div>

app/views/departments/_form.html.erb
<div class="container">
	<h1>New Department</h1>
	<%= form_with model: @department do |f| %>
		<%= f.text_field :name, placeholder: "Department Name" %>
		<%= f.submit "Create Department", class: "btn" %>
	<% end %>
</div>

app/views/departments/_modal.html.erb
<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <%= render 'projects/form', department: @department %>
  </div>
</div>

app/views/departments/edit.html.erb
<%= render 'form' %>

app/views/departments/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <h1>Company Dashboard</h1>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m3">
      <div class="card blue-grey lighten-5">
        <div class="card-content black-text">
          <span class="card-title">Company Info</span>
          <p>This is a company that does things and other stuff</p>
        </div>
        <div class="card-action">
          <p class="card-title black-text">Actions</p>
          <%= link_to "New Department", new_department_path %>
          <p class="card-title black-text">Departments</p>
          <div class="collection department">
            <% @departments.each do |department| %>
              <%= link_to department.name, department_path(department), class: "collection-item department-#{department.id} " %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="card blue-grey lighten-5">
        <div class="card-content black-text">
          <span class="card-title black-text">Departments</span>
          <div class="row">
             <% @departments.each do |department| %>
              <%= render department %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col s12 m3">
      <div class="card blue-grey lighten-5">
        <div class="card-content black-text">
          <span class="card-title">Managers</span>
          <p>Department managers listed</p>
        </div>
        <div class="card blue-grey lighten-5">
          <div class="card-content black-text">
            <span class="card-title">Employees</span>
            <ul class="collapsible" data-collapsible="accordion">
              <% @users.each do |user| %>
                <%= render user %> <!-- current push -->
              <% end %>
            </ul>
          </div>
        </div>  
      </div>
    </div> <!-- end of column -->
  </div>
</div>

app/views/departments/new.html.erb
<%= render 'form' %>

app/views/departments/show.html.erb
<!-- Collumn 1 - shows all dept info and action items to be taken on this dash -->
<div class="row">
  <div class="col">
    <h1><%= @department.name %> Department</h1>
  </div>
</div>
<div class="row">
  <div class="col s12 m3">
    <div class="card blue-grey lighten-5">
      <div class="card-content black-text">
        <span class="card-title">Department: <%= @department.name %></span>
        <%= link_to "Edit Department", edit_department_path(@department) %>
        <br>
        <%= link_to "Delete Department", @project, method: :delete, class: "destroy_project" %>
      </div>
      <div class="card-action">
        <%= link_to "Create Project", '#modal1', class: "modal-trigger" %>
        <br>
      </div>
    </div>
  </div>
  <!-- modal for creating projects -->
  <%= render 'modal' %>
  
  <!-- Collumn 2 - should loop through every project that belongs to this department -->

  <!-- start of the projects showing -->
  <div class="col s12 m6">
    <div class="card blue-grey lighten-5">
      <div class="card-content black-text">
        <span class="card-title">Projects</span>
        <div class="row">
           <% @projects.each do |project| %>
            <%= render project %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- collumn 3- should loop through and show every employee that belongs to this department as well as show team points -->
  <!-- Team points -->
  <div class="col s12 m3">
    <div class="card blue-grey lighten-5">
      <div class="card-content">
        <span class="card-title black-text">Team Points</span>
          
      </div>
    </div>
  </div>
  <!-- team -->
  <div class="col s12 m3">
    <div class="card blue-grey lighten-5">
      <div class="card-content black-text">
        <span class="card-title">Team</span>
        <ul class="collapsible" data-collapsible="accordion">
          <% @users.each do |user| %>
            <%= render user %>  <!-- current push -->
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/projects/_edit_form.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col">
			<h4>Edit Project</h4>
		</div>
	</div>
	<div class="row">
		<%= form_with model: @project, class: "col s12", method: :put do |f| %>
			<%= f.hidden_field :department_id, value: @department.id %>
			<%= f.text_field :name, placeholder: :name %>
			<%= f.text_field :description, placeholder: :description %>
			<%= f.date_field :deadline, placeholder: :deadline %>
			<%= f.collection_select(:user_ids, @users, :id, :name, {prompt: true}, {multiple: true}) %>
			<div class="modal-footer">
				<%= f.submit "Submit", class: "modal-action modal-close waves-effect waves-green btn-flat" %>
		  </div>
		<% end %>
	</div>
</div>

app/views/projects/_form.html.erb
<div class="container-fluid new_project">
	<div class="row">
		<div class="col">
			<h4>New Project</h4>
		</div>
	</div>
	<div class="row">
		<%= form_with model: @project_new, class: "col s12" do |f| %>
			<%= f.hidden_field :department_id, value: @department.id %>
			<%= f.text_field :name, placeholder: :name %>
			<%= f.text_field :description, placeholder: :description %>
			<%= f.date_field :deadline, placeholder: :deadline %>
			<%= f.collection_select(:user_ids, @users, :id, :name, {prompt: true}, {multiple: true}) %>
			<div class="modal-footer">
				<%= f.submit "Submit", class: "modal-action modal-close waves-effect waves-green btn-flat" %>
		  </div>
		<% end %>
	</div>
</div>

app/views/projects/_modal.html.erb
<div id="new-project-modal" class="modal">
  <div class="modal-content">
    <%= render 'tasks/form', project: @project %>
  </div>
</div>

app/views/projects/_project.html.erb
<div class="col s6 card project">
  <div class="card-content">
    <span class="card-title">
    	<%= link_to project.name, project_path(project) %></span>
      <% project.tasks.all.each do |task| %>
        <ul class="collapsible" data-collapsible="accordion">
          <%= render task %>
        </ul>
      <% end %>
  </div>
  <div class="card-action">
      <%= link_to "Edit", edit_project_path(project) %>
      <%= link_to "Delete", project, method: :delete, remote: :true, class: "destroy_project float_right" %>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/project.html.erb
<div class="row">
  <div class="col s6 m6">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><%= project.name %></span>
         <% project.tasks.all.each do |task| %>
           <div class="collection">
              <%= link_to task.name, project, class: "collection-item task-#{task.id}" %>
            </div>
         <% end %>
      </div>
      <div class="card-action">
        <%= link_to "Edit", edit_project_path(project) %>
        <%= link_to "Delete", project_path(project), method: :destroy %>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
  <div class="row">
    <div class="col">
      <h1><%= @project.name %> Dashboard</h1>
    </div>
  </div>
    <div class="row">
      <div class="col s12 m3">
        <div class="card blue-grey lighten-5">
          <div class="card-content black-text">
            <span class="card-title">Project: <%= @project.name %></span>
            <p><strong>Description:</strong></p>
            <p><%= @project.description %></p>
            <br>
            <p><strong>Deadline:</strong></p>
            <p><%= @project.deadline %></p>
            <br>
            <%= link_to "Edit Project", edit_project_path(@project) %>
            <br>
             <%= link_to "Delete Project", @project, method: :delete, class: "destroy_project" %>
          </div>
          <div class="card-action">
            <span class="card-title">Department</span>
            <br>
            <%= link_to @department.name, department_path(@department) %>
            <br>
            <br>  
            <span class="card-title">Project Actions</span>
            <br>
            <%= link_to "Create Task", '#new-project-modal', class: "modal-trigger" %> 
            <br>
            <%= link_to "Edit Project Team", '#edit_team_modal', class: "modal-trigger" %> 
          </div>
        </div>
      </div> <!-- end of column -->
      <!--*********** modals *************-->
      <!-- create task modal -->
      <%= render 'modal' %>
      <!-- assign team modal -->
      <div id="edit_team_modal" class="modal">
        <div class="modal-content">
          <div class="card-title">Assign Team</div>
          <%= form_with model: @project do |f| %>
            <p><em>Uncheck team members you would like to remove</em></p>
            <%= f.collection_select(:user_ids, @users, :id, :name, {prompt: true}, {multiple: true}) %>
            <%= f.submit %>
          <% end %>
        </div>
      </div>
      <!-- start of displaying tasks -->
      <div class="col s12 m6">
        <div class="card blue-grey lighten-5">
          <div class="card-content black-text">
            <span class="card-title black-text">Tasks</span>
            <div class="row tasks_display">
              <%= render 'tasks/tasks' %>
            </div>
          </div>
        </div>
      </div> <!-- end of column -->
      <div class="col s12 m3">
        <div class="card blue-grey lighten-5">
          <div class="card-content black-text">
            <span class="card-title">Team</span>
            <ul class="collapsible" data-collapsible="accordion">
              <% @team.each do |user| %>
                <%= render user %>
              <% end %>
          </ul>
          </div>
        <div class="card blue-grey lighten-5">
          <div class="card-content black-text">
            <span class="card-title">All Employees</span>
            <ul class="collapsible" data-collapsible="accordion">
              <% @users.each do |user| %>
                <%= render user %>
              <% end %>
            </ul>
          </div>
        </div>  
    </div>
  </div>
</div> <!-- end of row -->

app/views/tasks/_edit_form.html.erb
<div class="container-fluid edit_task">
	<%= form_with model: @task do |f| %>
		<%= f.hidden_field :project_id, value: @project.id %>
		<%= f.text_field :name, placeholder: :name %>
		<%= f.text_field :description, placeholder: :description %>
		<%= f.date_field :deadline, placeholder: :deadline %>
		<%= f.collection_select(:user_ids, @users, :id, :name, {prompt: true}, {multiple: true}) %>
		<%= f.submit class: "modal-close" %>
	<% end %>
</div>

app/views/tasks/_form.html.erb
<div class="container-fluid new_task">
	<%= form_with model: Task.new do |f| %>
		<%= f.hidden_field :project_id, value: @project.id %>
		<%= f.text_field :name, placeholder: :name %>
		<%= f.text_field :description, placeholder: :description %>
		<%= f.date_field :deadline, placeholder: :deadline %>
		<%= f.collection_select(:user_ids, @users, :id, :name, {prompt: true}, {multiple: true}) %>
		<div class="modal-footer">
			<%= f.submit class: "modal-close" %>
		</div>
	<% end %>
</div>

app/views/tasks/_modal.html.erb
<div id="modal2" class="modal">
  <div class="modal-content">
    <%= render 'tasks/form' %>
  </div>
  <div class="modal-footer">
  </div>
</div>

app/views/tasks/_task.html.erb
<!-- this must be wrapped in: <ul class="collapsible" data-collapsible="accordion"></ul> -->
<!-- task-<task.id > must stay in third class position -->
<li id="task-<%= task.id %>" data-complete="<%= task.complete %>" data-id="<%= task.id %>" class="task task_container task-<%= task.id %> ">
	<div class="collapsible-header">
		<%= task.name %>
		<div class="switch">
			<label>
				<input type="checkbox" <%= (task.complete ? 'checked' : '') %>>
				<span class="lever"></span>
				Complete
			</label>
		</div>
	</div>
  <div class="collapsible-body">
  	<span class="row">
  		<div class="col s6">
  		    	<p><%= task.description %></p>
  		    	<p><%= task.deadline %></p>
  		</div>
  		<span class="col s6">
  			<% task.task_users.each do |assignment| %>
  				<p class="task_assignment"><%= assignment.user.name %></p>
  			<% end %>
  		</span>
			<span class="col 12">
				<p><strong>Assign Users To Task</strong></p>
				<%= form_with model: task, class: "update_team" do |f| %>  
          <p><em>Uncheck team members you would like to remove</em></p>
          <%= f.collection_select(:user_ids, @users, :id, :name, {prompt: true}, {multiple: true}) %>
          <%= f.submit "Update Team", class: 'btn' %>
        <% end %>
			</span>
  	</span>
	</div>
  <div class="card-action">
      <%= link_to "Edit", '#modal_task', class: "modal-trigger" %>
      <%= link_to "Delete", task, method: :delete, remote: :true, class: "destroy_task float_right" %>
  </div>
</li>
<!-- Edit task modal -->
<div id="modal_task" class="modal">
  <div class="modal-content">
    <%= form_with model: task, class: "update_task" do |f| %>
      <%= f.text_field :name, placeholder: :name %>
      <%= f.text_field :description, placeholder: :description %>
      <%= f.date_field :deadline, placeholder: :deadline %>
      <%= f.collection_select(:user_ids, @users, :id, :name, {prompt: true}, {multiple: true}) %>
      <div class="modal-footer">
        <%= f.submit class: 'modal-close' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_tasks.html.erb
<ul class="collapsible tasks" data-collapsible="accordion">
  <% @tasks.each do |task| %>
    <%= render task %>
  <% end %>
</ul>

app/views/tasks/create.js.erb
$('.tasks').append("<%= j render @task %>");
$('.new_task').trigger('reset');

app/views/tasks/edit.html.erb
<div class="container-fluid edit_task">
	<%= form_with model: @task do |f| %>
		<%= f.hidden_field :project_id, value: @project.id %>
		<%= f.text_field :name, placeholder: :name %>
		<%= f.text_field :description, placeholder: :description %>
		<%= f.date_field :deadline, placeholder: :deadline %>
		<%= f.collection_select(:user_ids, @users, :id, :name, {prompt: true}, {multiple: true}) %>
		<%= f.submit class: "modal-close" %>
	<% end %>
</div>

app/views/tasks/toggle.js.erb
$('#points_display').html("<%= j render 'users/points' %> ");
console.log('This is the erb');

app/views/tasks/update.js.erb
$('.tasks_display').html("<%= j render 'tasks/tasks' %>");
$('.collapsible').collapsible();
$('select').material_select();


 